### PR TITLE
Use llvmpipe for mesalib.

### PR DESCRIPTION
**Pull request by danlipsa**
Fixes https://github.com/UV-CDAT/vcs/issues/210

### CODE REVIEW

**Comment by danlipsa** [comment]
@aashish24 @doutriaux1 Please review

**Comment by doutriaux1** [comment]
@danlipsa instead of this we should just copy other the official recipe (whhich @sankhesh helped put together) which uses galleum. Or even better remove mesalib from here.

https://github.com/conda-forge/mesalib-feedstock/blob/master/recipe/build.sh

**Comment by danlipsa** [comment]
@doutriaux1 You mean copy over the official recipe? How do you do that?

**Comment by doutriaux1** [comment]
@danlipsa no worries. I'm updating the official recipe (and will add you to the list of maintainers) and will delete mesalib from here. In the mean time could you please take a look at the vtk-cdat build.sh and see which modules we could disable. Looks like we have disk-space issues on travis (although the switch from DEBUG to RELAESE might help with that!)

**Comment by doutriaux1** [comment]
mac build leads to:
```
Python 2.7.13 | packaged by conda-forge | (default, May  2 2017, 13:29:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
x.plot(s>>> x.plot(s)
Process 27068 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffe8)
    frame #0: 0x0000000109d49e5e libLLVM-3.3.dylib`llvm::EngineBuilder::selectTarget() + 256
libLLVM-3.3.dylib`llvm::EngineBuilder::selectTarget:
->  0x109d49e5e <+256>: movq   -0x18(%r8), %r9
    0x109d49e62 <+260>: movq   %r9, -0x48(%rbp)
    0x109d49e66 <+264>: movq   0x60(%rbx), %rdx
    0x109d49e6a <+268>: movq   %rdx, -0x40(%rbp)
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xffffffe8)
  * frame #0: 0x0000000109d49e5e libLLVM-3.3.dylib`llvm::EngineBuilder::selectTarget() + 256
    frame #1: 0x0000000108edb9ac libOSMesa32.8.dylib`lp_build_create_jit_compiler_for_module + 2332
    frame #2: 0x0000000108ed879c libOSMesa32.8.dylib`init_gallivm_engine + 108
    frame #3: 0x0000000108ed846b libOSMesa32.8.dylib`init_gallivm_state + 443
    frame #4: 0x0000000108ed827c libOSMesa32.8.dylib`gallivm_create + 76
    frame #5: 0x0000000108fa065e libOSMesa32.8.dylib`generate_variant + 174
    frame #6: 0x0000000108f9faa4 libOSMesa32.8.dylib`llvmpipe_update_fs + 788
    frame #7: 0x0000000108f9e40a libOSMesa32.8.dylib`llvmpipe_update_derived + 170
    frame #8: 0x0000000108f7842b libOSMesa32.8.dylib`llvmpipe_draw_vbo + 139
    frame #9: 0x0000000108d4c6f9 libOSMesa32.8.dylib`cso_draw_vbo + 89
    frame #10: 0x0000000108d4c758 libOSMesa32.8.dylib`cso_draw_arrays + 88
    frame #11: 0x0000000108ac9ee4 libOSMesa32.8.dylib`st_draw_quad + 980
    frame #12: 0x0000000108aa844a libOSMesa32.8.dylib`clear_with_quad + 1754
    frame #13: 0x0000000108aa79e0 libOSMesa32.8.dylib`st_Clear + 992
    frame #14: 0x000000010884431c libOSMesa32.8.dylib`_mesa_Clear + 796
    frame #15: 0x0000000108f5d99c libOSMesa32.8.dylib`glClear + 44
    frame #16: 0x0000000107d31dcf libvtkRenderingOpenGL-8.1.1.dylib`vtkOpenGLRenderer::Clear() + 143
    frame #17: 0x0000000107d08d5c libvtkRenderingOpenGL-8.1.1.dylib`vtkOpenGLCamera::Render(vtkRenderer*) + 1324
    frame #18: 0x0000000105652f3a libvtkRenderingCore-8.1.1.dylib`vtkRenderer::UpdateCamera() + 618
    frame #19: 0x0000000107d2f7ad libvtkRenderingOpenGL-8.1.1.dylib`vtkOpenGLRenderer::DeviceRender() + 157
    frame #20: 0x00000001056526a3 libvtkRenderingCore-8.1.1.dylib`vtkRenderer::Render() + 1235
    frame #21: 0x000000010565169b libvtkRenderingCore-8.1.1.dylib`vtkRendererCollection::Render() + 139
    frame #22: 0x000000010565c26c libvtkRenderingCore-8.1.1.dylib`vtkRenderWindow::DoStereoRender() + 140
    frame #23: 0x000000010565b584 libvtkRenderingCore-8.1.1.dylib`vtkRenderWindow::Render() + 596
    frame #24: 0x00000001053e5c19 libvtkRenderingCorePython27D-8.1.1.dylib`PyvtkRenderWindow_Render(_object*, _object*) + 137
    frame #25: 0x0000000100142f73 libpython2.7.dylib`PyEval_EvalFrameEx + 30563
    frame #26: 0x000000010013b3b2 libpython2.7.dylib`PyEval_EvalCodeEx + 1666
    frame #27: 0x00000001000c40ac libpython2.7.dylib`function_call + 364
    frame #28: 0x000000010009ddc3 libpython2.7.dylib`PyObject_Call + 99
    frame #29: 0x000000010014381c libpython2.7.dylib`PyEval_EvalFrameEx + 32780
    frame #30: 0x000000010013b3b2 libpython2.7.dylib`PyEval_EvalCodeEx + 1666
    frame #31: 0x0000000100147996 libpython2.7.dylib`fast_function + 118
    frame #32: 0x000000010014299a libpython2.7.dylib`PyEval_EvalFrameEx + 29066
    frame #33: 0x000000010013b3b2 libpython2.7.dylib`PyEval_EvalCodeEx + 1666
    frame #34: 0x0000000100147996 libpython2.7.dylib`fast_function + 118
    frame #35: 0x000000010014299a libpython2.7.dylib`PyEval_EvalFrameEx + 29066
    frame #36: 0x000000010013b3b2 libpython2.7.dylib`PyEval_EvalCodeEx + 1666
    frame #37: 0x000000010013ad26 libpython2.7.dylib`PyEval_EvalCode + 54
    frame #38: 0x00000001001699b6 libpython2.7.dylib`PyRun_InteractiveOneFlags + 406
    frame #39: 0x000000010016946e libpython2.7.dylib`PyRun_InteractiveLoopFlags + 206
    frame #40: 0x000000010016930b libpython2.7.dylib`PyRun_AnyFileExFlags + 139
    frame #41: 0x000000010017f75c libpython2.7.dylib`Py_Main + 3084
    frame #42: 0x00007fffeac88235 libdyld.dylib`start + 1
(lldb) 
```

**Comment by danlipsa** [comment]
@doutriaux1 Do you use llvm from conda or the system one?

**Comment by doutriaux1** [comment]
llvm from conda. both build and run tell to use it.

works fine on linux

**Comment by doutriaux1** [comment]
@danlipsa I had not diabled opengl in the conda-recipe. Local build seems to fix the mac mesa, pushing up to conda-forge, we'll see.

**Comment by danlipsa** [comment]
@doutriaux1 Sounds good.

**Comment by doutriaux1** [comment]
@danlipsa local build leads to a mesalib that works for me, but once built on travis it's not compatible. I suspect different llvm/sdk version, trying locally with llvmdev firstand might try to push this as well.

**Comment by danlipsa** [comment]
@doutriaux1 We don't use:

vtkFiltersSMP

There may be others but they don't jump at me. I looked at a few that looked promising, but they were used by other modules which we use. For instance vtkFiltersAMR is used by vtkFiltersFlowPaths

**Comment by doutriaux1** [comment]
@danlipsa I actually don't think the volume is an issue anymore. But we are failing the build on travis's build. I will try to up travis's XCode/SDK to see if it helps.

**Pull request merged**
