### PR TITLE
Use vtkweb

### PR DESCRIPTION
**Pull request by danlipsa**

### CODE REVIEW

**Comment by danlipsa** [comment]
@doutriaux1 @mattben @aashish24 Please review. This is needed to switch to vtkweb based vcs.js

**Comment by doutriaux1** [comment]
@danlipsa I guess i should go ahead and update nighlty versions of VTK correct?

**Comment by danlipsa** [comment]
@doutriaux1 Yes, that is correct.

**Comment by danlipsa** [comment]
@doutriaux1 We need to update both vtk-cdat and vcs-js. Thanks!

**Comment by doutriaux1** [comment]
@danlipsa ok will update vcs-js as well.

**Pull request merged**
