### PR TITLE
Updated acme_diags, and nco.

### PR DESCRIPTION
**Pull request by zshaheen**

### CODE REVIEW

**Comment by xylar** [comment]
@doutriaux1, do you have time to merge this?  I just started at LANL this week and have a mountain of paperwork to get through so I'm having trouble finding time.

**Comment by zshaheen** [comment]
@xylar I believe that @doutriaux1 was waiting for 4.6.9 of `nco` to be avaiable on `conda-forge`. As we see [here](https://anaconda.org/conda-forge/nco/files), it is. So I think he can merge it now.

**Comment by doutriaux1** [comment]
@xylar yep done and putting it on aims4 and acme1

**Comment by xylar** [comment]
Great, yeah, the OSX builds of NCO seem to be taking ages.  I don't have enough experience with Travis-CI to know if this is normal or not.

**Pull request merged**
