### PR TITLE
Upgrade vcs-js: Add a list of subset operations to a variable specifi…

### PR DESCRIPTION
**Pull request by danlipsa**
…cation.

### CODE REVIEW

**Comment by danlipsa** [comment]
@mattben @doutriaux1 One more. We'll need to build/push this package to conda. Thanks!

**Comment by doutriaux1** [comment]
@danlipsa @mattben we should really add atest suite (or not) and use one of our autoupload script like there: https://github.com/UV-CDAT/cdms/blob/master/scripts/conda_upload.sh which is called from our .travis.yml

**Comment by doutriaux1** [comment]
@danlipsa is this a nighlty or do you want to tag it `0.5` ?

**Comment by danlipsa** [comment]
> is this a nighlty or do you want to tag it 0.5
I have a hard time deciding when I should bump which version. This one reason I like to have the SHA appended. Maybe at point (when we release vcdat) we'll make this 1.0.
Maybe I should start using semantic versioning: http://semver.org/

> we should really add atest suite
I agree. We have some tests added by @jbeezley long time ago. I think they are API only, no images. I have to see what we have in there.

> use one of our autoupload script like there: https://github.com/UV-CDAT/cdms/blob/master/scripts/conda_upload.sh which is called from our .travis.yml
So, if I add a script like that, travis will build my packages next time I merge something to master?

**Pull request merged**
